service: hello

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  memorySize: 128

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /sayhi
          method: get

